type = "webpack"
name = "dev-rust"
account_id = ""
zone_id = "6db4a31ca69842edd00ed1d171645ae0"
route = "https://dev-rust.kvarteretankan13.online/*"
vars = { ENVIRONMENT = "dev" }
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
name = "rust"
vars = { ENVIRONMENT = "production" }
route = "https://rust.kvarteretankan13.online/*"
workers_dev = false