name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  TRUNK_VER: 'v0.7.4'
  BINARYEN_VER: 'version_97'
  BINDGEN_VER: '0.2.68'
  WRANGLER_VER: 'v1.12.2'
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install wasm-bindgen-cli
        run: wget -qO- https://github.com/rustwasm/wasm-bindgen/releases/download/${BINDGEN_VER}/wasm-bindgen-${BINDGEN_VER}-x86_64-unknown-linux-musl.tar.gz | sudo tar -xzf- --strip=1 -C /bin/

      - name: Install Trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/${TRUNK_VER}/trunk-x86_64-unknown-linux-gnu.tar.gz | sudo tar -xzf-

      - name: Install Binaryen
        run: wget -qO- https://github.com/WebAssembly/binaryen/releases/download/${BINARYEN_VER}/binaryen-${BINARYEN_VER}-x86_64-linux.tar.gz | sudo tar -xzf- --strip=1 -C /bin/

      - name: Install Clippy
        run: rustup component add clippy

      - name: Install Wrangler
        run: wget -qO- https://github.com/cloudflare/wrangler/releases/download/${WRANGLER_VER}/wrangler-${WRANGLER_VER}-x86_64-unknown-linux-musl.tar.gz | sudo tar -xzf- --strip=1 -C /bin/

      - name: Run Clippy
        run: cargo clippy

      - name: Cargo test
        run: cargo test --verbose

      - name: Wasm test Firefox
        run: wasm-pack test --firefox

      - name: Wasm test Chrome
        run: wasm-pack test --chrome

      - name: Clean & Build
        run: ./trunk clean && ./trunk build --release

      - name: Optimize output
        run: find dist -iname '*.wasm' -exec mv {} ankan.wasm \; -exec wasm-opt -Oz -o {} ankan.wasm \;

      - name: Deploy to dev
        run: wrangler publish
